INSERT INTO CURRENCY_EXCHANGE (ID,EXCHANGE_VALUE,FROM_CURRENCY,TO_CURRENCY,PORT) VALUES (1001,65,'USD','INR',8000);
INSERT INTO CURRENCY_EXCHANGE (ID,EXCHANGE_VALUE,FROM_CURRENCY,TO_CURRENCY,PORT) VALUES (1002,75,'EUR','INR',8000);
INSERT INTO CURRENCY_EXCHANGE (ID,EXCHANGE_VALUE,FROM_CURRENCY,TO_CURRENCY,PORT) VALUES (1003,35,'CAD','INR',8000);